### ISSUE TITLE
If submodule url is relative and ends with “.git”, file tab page gets error 500.

### ISSUE THREAD

**Issue by andrewwutw** [gitlabhq/gitlabhq#7554]
If url in .gitmodules file is relative (starts with “../“) and ends with “.git”, like this :

    [submodule "hello"]
    	path = hello
    	url = ../hello.git

Then the file tab page in GitLab will show error 500.

I uploaded the repo into GitLab site (running Enterprise Edition 7.2.0.rc2-ee f41eef1 ):

https://gitlab.com/andrewwu.tw/submodule-test

And its file tab page shows error 500:

https://gitlab.com/andrewwu.tw/submodule-test/tree/master

But, if I add a slash (/) in the end of url, like this :

    [submodule "hello"]
    	path = hello
    	url = ../hello.git/

This file tab page in GitLab is ok.

I uploaded the modified repo into GitLab, too:

https://gitlab.com/andrewwu.tw/submodule-test2

And its file tabs page is ok:

https://gitlab.com/andrewwu.tw/submodule-test2/tree/master

GitHub can handle both form of submodule url without any problem, ex :

https://github.com/andrewwutw/submodule-test
https://github.com/andrewwutw/submodule-test2

**Comment by DouweM** [comment]
Fixed by 6331759735074e2b14d398dfa1804cfa1f241d49!

**Comment by andrewwutw** [comment]
@DouweM 

Sorry, I think it is not really fixed.

If URL in .gitmodules file is only relative to ONLY one parent level and ends with “.git”, like this :
````
[submodule "hello"]
    path = hello
    url = ../hello.git
````

Then the problem is not fixed yet. You can check this repo in GitLab server(running 7.10.0.rc4-ee b58b905):

https://gitlab.com/andrewwu.tw/submodule-test

Its file tab page shows error 500:

https://gitlab.com/andrewwu.tw/submodule-test/tree/master

But, if the URL is relative to TWO parent levels and ends with ".git", like this:
````
[submodule "hello"]
    path = hello
    url = ../../hello.git
````
Then there is no problem. I think it is what you fixed.

You can check this repo here :

https://gitlab.com/andrewwu.tw/submodule-test3

File tab page is ok.

https://gitlab.com/andrewwu.tw/submodule-test3/tree/master

**Comment by stanhu** [comment]
@andrewwutw, thanks for testing this out. It looks like the issue is that relative submodule links on personal projects don't work but relative submodule links with projects owned by a group do.

I'll submit a MR to fix this.

**Comment by andrewwutw** [comment]
Fixed in v7.11 , thanks. :smile:

**Comment by matanster** [comment]
I think hyperlinks are not currently showing at all, in the case discussed here.
See [here](https://github.com/CANVE/extractor).

(The submodule definitions are of course in https://github.com/CANVE/extractor/blob/master/.gitmodules)
