### ISSUE TITLE
Web editor removes newline at the end

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8706]
**Information:**
Whenever I add newline in the end of a file, the preview changes doesn't show the newly added newline. Also whenever deleting that newline, previewing that changes doesn't show the deleted newline.

**Screenshot:**
**Preview**
![img1](https://www.anonimg.com/img/737ceb937805d565dcff93a4c996baed.jpg)
**Edit View**
![img2](https://www.anonimg.com/img/2cd53525e87fb391771084e53188d1ac.jpg)

**Comment by rmetzler** [comment]
I think I experience a similar issue. Gitlab's web editor doesn't respect existing newlines at end of file.
I edited the README.md file in the web editor, but didn't change the last lines. When I had a look at the commit it says
```
\ No newline at end of file
```

**Comment by X-Coder** [comment]
Same for me, even leading whitespaces gets removed.

I tried it by creating a new file using gitlab, commited the file, opened the file again and just looked at preview without changing anything. I guess the same is happening when we try to edit some other existing files.

I commited 2 lines in a new file like this using the web editor ([WS]=Whitespace, [LF]=LineFeed):
[WS][WS][WS][WS]testline1[LF]
testline2[LF]

The failed result in the preview:
testline1[LF]
testline2

As you can see in the result, the leading whitespaces were removed and the last linefeed.

**Comment by kylekatarnls** [comment]
My 2 cents, it should also respect the .editorconfig if present.

**Comment by eddiemonge** [comment]
I agree with it respecting .editorconfig if present but not really sure how that work. It should just not remove anything from the file unless the user has removed it.

**Comment by Igloczek** [comment]
PR #9422 looks like solution, but rejected because author don't test well the code.

**Comment by dosire** [comment]
Also mentioned in https://gitlab.com/gitlab-org/gitlab-ce/issues/3784#note_2837999

**Comment by stanhu** [comment]
I think this was fixed in GitLab 8.3 via 5afe03315.

**Comment by amchercashin** [comment]
Can report that this issue is still present, I was trying to edit [this](https://github.com/tensorflow/tensorflow/edit/master/tensorflow/tools/docker/notebooks/2_getting_started.ipynb) file. Try to change something and you'll get:
![newline_delete](https://cloud.githubusercontent.com/assets/8727497/14072560/65667572-f4ca-11e5-954b-a2b652ed7565.png)

**Comment by stanhu** [comment]
@amchercashin First, this looks like a GitHub screenshot, not a GitLab screenshot. Second, the diff seems to suggest that a newline was added where there was not one previously.

**Comment by amchercashin** [comment]
@stanhu Okay, now I see it. Really sorry :)
