### ISSUE TITLE
Upgrade Gitlab from 6.1 to 7.8

### ISSUE THREAD

**Issue by MLChen** [gitlabhq/gitlabhq#8874]
Hi there,

I'm follow this [guide](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/6.x-or-7.x-to-7.8.md) to upgrade my gitlab 6.1, when do db migration (Step 7) it happed error.

git@gitlab:~/gitlab$ bundle exec rake db:migrate RAILS_ENV=production
== 20140903115954 MigrateToNewShell: migrating ================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

"""
Failed to rewrite gitlab-shell hooks in repositories/srv/git/gitlab/db/migrate/20140903115954_migrate_to_new_shell.rb:7:in `change'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:595:in `exec_migration'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:578:in `block in migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:577:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:752:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:1040:in `ddl_transaction'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:953:in `block in migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `each'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `up'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:785:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
"""

How to solve this problem and Thanks :)

**Comment by Razer6** [comment]
@MLChen Can you try rerunning the database migration again?

**Comment by MLChen** [comment]
@Razer6 Its show the same error..

"""
git@gitlab:~/gitlab$ bundle exec rake db:migrate RAILS_ENV=production
== 20140903115954 MigrateToNewShell: migrating ================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Failed to rewrite gitlab-shell hooks in repositories/srv/git/gitlab/db/migrate/20140903115954_migrate_to_new_shell.rb:7:in `change'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:595:in `exec_migration'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:578:in `block in migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:577:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:752:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:1040:in `ddl_transaction'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:953:in `block in migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `each'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `up'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:785:in `migrate'
/srv/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
"""

**Comment by Razer6** [comment]
@MLChen  This is a known bug that will be fixed with 7.8.2
In the meantime you can apply this fix ontop of 7.8.1 to sucessfully complete the update:
https://gitlab.com/gitlab-org/gitlab-ce/commit/4803af45dfbd516890b3ab31fa55b93009174d63

**Comment by MLChen** [comment]
@Razer6 Sorry, I'm not sure how to do the correct step.

'''
$ sudo -u git -H git checkout v7.8.1
$ sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production
'''

Is it correct? but show the same error too.

**Comment by Razer6** [comment]
This was fixed in 7.8.2 so closing this

**Comment by maestromani** [comment]
even after editing the file it still fails.... is there any other solution ?

what happens to database as we are in middle of upgrade.

**Comment by mijoharas** [comment]
Just to help anyone else that might've been looking for this, this error is also thrown if you have the wrong path for your gitlab-shell. (which can happen if that moves and you don't notice.
