### ISSUE TITLE
Namespace.clean_path removes last character from username with ldap authentication

### ISSUE THREAD

**Issue by darix** [gitlabhq/gitlabhq#9098]
```
::Namespace.clean_path("foo@example.com".match(/^[^@]*/)[0].parameterize)
```

Expected output:
"foo"

Actual output:
"fo"

master: gitlab-ce-7.10.0+git1428299238.526b28d

@randx any ideas on this or is this someone else part?

**Comment by darix** [comment]
```
diff --git a/app/models/namespace.rb b/app/models/namespace.rb
index dd74165..fcce8b4 100644
--- a/app/models/namespace.rb
+++ b/app/models/namespace.rb
@@ -62,7 +62,7 @@ class Namespace < ActiveRecord::Base
       path.gsub!(/@.*\z/,             "")
       path.gsub!(/\.git\z/,           "")
       path.gsub!(/\A-/,               "")
-      path.gsub!(/.\z/,               "")
+      path.gsub!(/\.\z/,              "")
       path.gsub!(/[^a-zA-Z0-9_\-\.]/, "")
 
       counter = 0
```

This fixes it for us

**Comment by randx** [comment]
@DouweM do you remember if we fixed it?

**Comment by DouweM** [comment]
@randx Nope, just checked and the problem is still there. His fix is correct.

**Comment by randx** [comment]
@DouweM can you submit MR?

**Comment by DouweM** [comment]
@randx Looks like he already did: https://github.com/gitlabhq/gitlabhq/pull/9104. The other changes there make sense as well.

**Comment by randx** [comment]
cool. I merged it
