### ISSUE TITLE
Compare doesn't work if branch name contains forward slash

### ISSUE THREAD

**Issue by 3rdcycle** [gitlabhq/gitlabhq#9105]
git branch names sometimes contain forward slashes. E.g. when using the _Git Flow_ implementation in Atlassian's _SourceTree_ branches have names like `feature/foo` or `hotfix/bar`. 

In GitLab _Compare View_ the forward slash always gets replaced with %2F and a message says "There isn't anything to compare." (tested on GitLab 7.9.1).

**Comment by stanhu** [comment]
This was fixed in 862e1e6f and should be available in GitLab v7.10 to be released on April 22.

**Comment by ahager** [comment]
This issue still exists in GitLab v7.10. As far as I can tell will 862e1e6 only fix this issue when deleting a branch, but not when they get compared.

**Comment by pierrebeitz** [comment]
+1 still does not work in 7.10
