### ISSUE TITLE
Recently updated issue list sort not working.

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#9124]
Stop me if I'm wrong but if I add just a comment to an issue, this issue should be on top list if I sort it by "Recently updated"?

This is not working on Gitlab 7.9. Just showing the list without any sort effect.

Regards.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by bbodenmiller** [comment]
@Razer6 this still exists on 8.0.4. Take a look at https://gitlab.com/gitlab-org/gitlab-ce/issues?assignee_id=&author_id=&label_name=&milestone_id=&scope=all&sort=updated_desc&state=opened compared to https://gitlab.com/gitlab-org/gitlab-ce/activity and you will see issues with the most recent activity do not appear at the top of the list.

**Comment by bbodenmiller** [comment]
Updated details at https://gitlab.com/gitlab-org/gitlab-ce/issues/1750 which is duplicate of this issue.
